AllCops:
  DisplayCopNames: true
  Exclude:
    - vendor/**
    - metadata.rb
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Style/Documentation:
  Enabled: false
Style/Encoding:
  EnforcedStyle: always
  Enabled: true
Style/ExtraSpacing:
  Exclude:
    - attributes/hardening.rb
Style/NumericLiterals:
  MinDigits: 10
Style/RegexpLiteral:
  AllowInnerSlashes: true
Style/SpaceAroundOperators:
  Exclude:
    - attributes/hardening.rb
