AllCops:
  DisplayCopNames: true
  Exclude:
    - vendor/**
    - metadata.rb
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: true
Style/NumericLiterals:
  MinDigits: 10
